version : "3" #docker-compose的版本
services: #容器的集合
        mysql:
                image: mysql:intra-v1
                container_name: mysql
                privileged: true
                ports:
                        - 3306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: root 
        php:
                image: php:intra-v1
                container_name: php
                privileged: true
                ports: 
                        - 9000:9000
                links:
                        - mysql
                volumes:
                        - /docker/wwwroot:/www/web
        nginx:
                image:  nginx:intra-v1
                container_name: nginx
                privileged: true
                links:
                        - php
                ports:
                        - 80:80
                volumes:
                        - /docker/nginx/conf.d:/www/nginx/conf.d
                        - /docker/nginx/log:/www/nginx/log
                        - /docker/wwwroot:/www/web
